"""Add total_cost_jpy to asset

Revision ID: 0db90b21cb28
Revises: 82f381290557
Create Date: 2026-01-25 10:57:28.488472

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0db90b21cb28"
down_revision: Union[str, Sequence[str], None] = "82f381290557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "total_cost_jpy", sa.Numeric(precision=18, scale=2), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "total_cost_jpy")
    # ### end Alembic commands ###
